name: Main workflow

on:
  pull_request:
  push:

jobs:
  plugin_test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: asdf_plugin_test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: sd --help
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
